
package com.ocmc.web;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-12T12:57:58.468-04:00
 * Generated source version: 2.7.5
 * 
 */
public final class PriorityService_PriorityServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("com.ocmc.ws.services", "PriorityService");

    private PriorityService_PriorityServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PriorityService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PriorityService_Service ss = new PriorityService_Service(wsdlURL, SERVICE_NAME);
        PriorityService port = ss.getPriorityServiceImplPort();  
        
        {
        System.out.println("Invoking getPriority...");
        java.lang.Long _getPriority_id = Long.valueOf(3240974950849911543l);
        beans.ws.ocmc.com.PriorityType _getPriority__return = port.getPriority(_getPriority_id);
        System.out.println("getPriority.result=" + _getPriority__return);


        }
        {
        System.out.println("Invoking addPriority...");
        beans.ws.ocmc.com.PriorityType _addPriority_priority = new beans.ws.ocmc.com.PriorityType();
        _addPriority_priority.setPriorityID(1620629654);
        _addPriority_priority.setPriorityName("PriorityName-879187864");
        _addPriority_priority.setPriorityDesc("PriorityDesc618925814");
        java.lang.Long _addPriority__return = port.addPriority(_addPriority_priority);
        System.out.println("addPriority.result=" + _addPriority__return);


        }
        {
        System.out.println("Invoking getAllPriorities...");
        beans.ws.ocmc.com.PriorityCollectionType _getAllPriorities__return = port.getAllPriorities();
        System.out.println("getAllPriorities.result=" + _getAllPriorities__return);


        }
        {
        System.out.println("Invoking updatePriority...");
        beans.ws.ocmc.com.PriorityType _updatePriority_priority = new beans.ws.ocmc.com.PriorityType();
        _updatePriority_priority.setPriorityID(-1098010145);
        _updatePriority_priority.setPriorityName("PriorityName316297347");
        _updatePriority_priority.setPriorityDesc("PriorityDesc-1489313181");
        port.updatePriority(_updatePriority_priority);


        }

        System.exit(0);
    }

}
