package com.ocmc.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-12T12:57:58.562-04:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "com.ocmc.ws.services", name = "PriorityService")
@XmlSeeAlso({beans.ws.ocmc.com.ObjectFactory.class, ObjectFactory.class})
public interface PriorityService {

    @WebResult(name = "priority", targetNamespace = "")
    @RequestWrapper(localName = "GetPriority", targetNamespace = "com.ocmc.ws.services", className = "com.ocmc.web.GetPriority")
    @WebMethod(operationName = "GetPriority")
    @ResponseWrapper(localName = "GetPriorityResponse", targetNamespace = "com.ocmc.ws.services", className = "com.ocmc.web.GetPriorityResponse")
    public beans.ws.ocmc.com.PriorityType getPriority(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "AddPriority", targetNamespace = "com.ocmc.ws.services", className = "com.ocmc.web.AddPriority")
    @WebMethod(operationName = "AddPriority")
    @ResponseWrapper(localName = "AddPriorityResponse", targetNamespace = "com.ocmc.ws.services", className = "com.ocmc.web.AddPriorityResponse")
    public java.lang.Long addPriority(
        @WebParam(name = "priority", targetNamespace = "")
        beans.ws.ocmc.com.PriorityType priority
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetAllPriorities", targetNamespace = "com.ocmc.ws.services", className = "com.ocmc.web.GetAllPriorities")
    @WebMethod(operationName = "GetAllPriorities")
    @ResponseWrapper(localName = "GetAllPrioritiesResponse", targetNamespace = "com.ocmc.ws.services", className = "com.ocmc.web.GetAllPrioritiesResponse")
    public beans.ws.ocmc.com.PriorityCollectionType getAllPriorities();

    @RequestWrapper(localName = "UpdatePriority", targetNamespace = "com.ocmc.ws.services", className = "com.ocmc.web.UpdatePriority")
    @WebMethod(operationName = "UpdatePriority")
    @ResponseWrapper(localName = "UpdatePriorityResponse", targetNamespace = "com.ocmc.ws.services", className = "com.ocmc.web.UpdatePriorityResponse")
    public void updatePriority(
        @WebParam(name = "priority", targetNamespace = "")
        beans.ws.ocmc.com.PriorityType priority
    );
}
