
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ocmc.web;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-12T12:57:58.546-04:00
 * Generated source version: 2.7.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "PriorityService",
                      portName = "PriorityServiceImplPort",
                      targetNamespace = "com.ocmc.ws.services",
                      wsdlLocation = "resources/wsdl/priorityservice.wsdl",
                      endpointInterface = "com.ocmc.web.PriorityService")
                      
public class PriorityServiceImpl implements PriorityService {

    private static final Logger LOG = Logger.getLogger(PriorityServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ocmc.web.PriorityService#getPriority(java.lang.Long  id )*
     */
    public beans.ws.ocmc.com.PriorityType getPriority(java.lang.Long id) { 
        LOG.info("Executing operation getPriority");
        System.out.println(id);
        try {
            beans.ws.ocmc.com.PriorityType _return = new beans.ws.ocmc.com.PriorityType();
            _return.setPriorityID(-377586828);
            _return.setPriorityName("PriorityName-1507520453");
            _return.setPriorityDesc("PriorityDesc-2141090025");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ocmc.web.PriorityService#addPriority(beans.ws.ocmc.com.PriorityType  priority )*
     */
    public java.lang.Long addPriority(beans.ws.ocmc.com.PriorityType priority) { 
        LOG.info("Executing operation addPriority");
        System.out.println(priority);
        try {
            java.lang.Long _return = Long.valueOf(-4205558517247350956l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ocmc.web.PriorityService#getAllPriorities(*
     */
    public beans.ws.ocmc.com.PriorityCollectionType getAllPriorities() { 
        LOG.info("Executing operation getAllPriorities");
        try {
            beans.ws.ocmc.com.PriorityCollectionType _return = new beans.ws.ocmc.com.PriorityCollectionType();
            beans.ws.ocmc.com.PriorityCollectionType.Priorities _returnPriorities = new beans.ws.ocmc.com.PriorityCollectionType.Priorities();
            java.util.List<java.lang.Object> _returnPrioritiesPriority = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnPrioritiesPriorityVal1 = null;
            _returnPrioritiesPriority.add(_returnPrioritiesPriorityVal1);
            _returnPriorities.getPriority().addAll(_returnPrioritiesPriority);
            _return.setPriorities(_returnPriorities);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ocmc.web.PriorityService#updatePriority(beans.ws.ocmc.com.PriorityType  priority )*
     */
    public void updatePriority(beans.ws.ocmc.com.PriorityType priority) { 
        LOG.info("Executing operation updatePriority");
        System.out.println(priority);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
