package com.ocmc.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-12T12:57:58.578-04:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "PriorityService", 
                  wsdlLocation = "file:/C:/workspace/OCMC/ocmc-web/src/main/resources/wsdl/priorityservice.wsdl",
                  targetNamespace = "com.ocmc.ws.services") 
public class PriorityService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("com.ocmc.ws.services", "PriorityService");
    public final static QName PriorityServiceImplPort = new QName("com.ocmc.ws.services", "PriorityServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/OCMC/ocmc-web/src/main/resources/wsdl/priorityservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PriorityService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/OCMC/ocmc-web/src/main/resources/wsdl/priorityservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PriorityService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PriorityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PriorityService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PriorityService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PriorityService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PriorityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PriorityService
     */
    @WebEndpoint(name = "PriorityServiceImplPort")
    public PriorityService getPriorityServiceImplPort() {
        return super.getPort(PriorityServiceImplPort, PriorityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PriorityService
     */
    @WebEndpoint(name = "PriorityServiceImplPort")
    public PriorityService getPriorityServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PriorityServiceImplPort, PriorityService.class, features);
    }

}
